-- ============================================================
-- Resume Intelligence Platform - Phase 5 Schema Upgrade
-- Run this in the Supabase SQL Editor → https://supabase.co/dashboard/sql
--
-- Adds interview_questions.generation_source: tags each cached question batch as
-- either 'ai' (successfully generated by the configured LLM provider) or 'fallback'
-- (the AI call failed and static default questions were used instead).
--
-- This lets getQuestions() tell a genuine cached result apart from a stale fallback
-- batch and automatically retry generation, instead of permanently serving generic
-- static questions to a resume just because it happened to hit a transient AI failure
-- once. See interview-service.ts's getQuestions()/generateQuestions() for the logic.
--
-- This is additive and nullable — existing rows and existing code paths continue to
-- work unchanged (getQuestions() also does content-based detection as a second signal,
-- specifically to catch rows that predate this column).
-- ============================================================

ALTER TABLE interview_questions
  ADD COLUMN IF NOT EXISTS generation_source text;
